"use client";

import "./globals.css";
import "@mantine/core/styles.css";
import { MantineProvider } from "@mantine/core";
import { createContext, useState } from "react";

export const PageContext = createContext(null);

/* export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}; */

export default function RootLayout({ children }) {
    const [reportMetaData, setReportMetaData] = useState({
        title: "",
        date: "",
        author: "",
        department: "",
    });

    const [reportBodyText, setReportBodyText] = useState("");

    return (
        <html lang="tr" className="text-lg">
            <MantineProvider>
                <PageContext.Provider
                    value={{
                        reportMetaData,
                        setReportMetaData,
                        reportBodyText,
                        setReportBodyText,
                    }}
                >
                    <body className="">{children}</body>
                </PageContext.Provider>
            </MantineProvider>
        </html>
    );
}
